name: Deploy Marimo Notebook

on:
  push:
    branches: [master]
    paths:
      - choro_all.py
      - .github/workflows/deploy.yaml
      - public/converted_simp2.geojson
      - public/lau1-population-iz.csv
      - public/lau1-history-iz.csv
      - public/sk_data.pickle
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv add marimo

      - name: Export marimo notebook
        run: uv run marimo export html-wasm choro_all.py --output build --sandbox

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name:  Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
